### ISSUE TITLE
redmineのダークモードを探す

### ISSUE THREAD

**Issue by kqns91** [kqns91/til#12]
ラズパイにRedmineを立ててプラグインを追加できるようにし、いい感じのダークモードプラグインを見つけたい。

**Comment by kqns91** [comment]
### Redmineの構築

```
mkdir redmine
cd redmine
touch compose.yml
```

```yml
version: '3.8'
services:
  redmine:
    image: redmine:latest
    container_name: redmine
    ports:
      - 3000:3000
    volumes:
      - ./data/plugins:/usr/src/redmine/plugins
      - ./data/themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_MYSQL: ${REDMINE_DB_MYSQL}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD} 
      REDMINE_RELATIVE_URL_ROOT: /redmine
    depends_on:
      - redmine-db
    restart: always
    
  redmine-db:
    image: mariadb:latest
    container_name: redmine-db
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
```

```
docker-compose up -d
```

ポートフォーワードして、http://localhost:3000 にアクセスする。

<img width="1440" alt="スクリーンショット 2023-06-16 23 58 57" src="https://github.com/kqns91/til/assets/79058642/17a01ed9-cf3c-4743-870f-e60466821393">
