### ISSUE TITLE
microk8sを試す

### ISSUE THREAD

**Issue by kqns91** [kqns91/til#7]
ラズパイに入れてみる

boot設定を変更する

```
$ sudo vi /boot/firmware/nobtcmd.txt

cgroup_enable=memory cgroup_memory=1

$ sudo reboot now
```

インストール

```
$ sudo snap install microk8s --classic --channel=1.26
```

permission設定

```
$ sudo usermod -a -G microk8s $USER

$ newgrp microk8s
```

状態確認

```
$ microk8s.status
```

エイリアス設定

```
$ sudo snap alias microk8s.kubectl kubectl
```

コマンド実行確認

```
$ kubectl get node
NAME     STATUS   ROLES    AGE   VERSION
ubuntu   Ready    <none>   11m   v1.26.0
```

ここまでで構築完了。

**Comment by kqns91** [comment]
### ダッシュボードを見れるようにする

dashboard, dns, storageを有効化

```
$ microk8s.enable dashboard dns storage
```

10443ポートでdashboardを外に出す

```
$ microk8s kubectl port-forward -n kube-system service/kubernetes-dashboard --address 0.0.0.0 10443:443
```

firefoxからアクセス

https://192.168.0.38:10443

トークンを入力する。取得は↓から

```
microk8s kubectl -n kube-system describe secret $(microk8s kubectl -n kube-system get secret | grep default-token | awk '{print $1}')
```

### goアプリをデプロイする

docker imageを作成

```
$ docker build -t go-example .
```

docker imageをmicrok8sのctr(コンテナランタイム)にimportする

```
$ docker save go-example:latest -o go-example.tar
$ sudo microk8s ctr image import go-example.tar
```

manifest作成

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example
spec:
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - name: go-example
        image: go-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          hostPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-example
spec:
  type: LoadBalancer
  selector:
    app: go-example
  ports:
  - port: 8081
    targetPort: 8081
```

起動

```
$ kubectl apply -f k8s-resource.yml
```

<img width="1439" alt="スクリーンショット 2023-01-29 22 24 38" src="https://user-images.githubusercontent.com/79058642/215329223-ef98da86-7baa-42ca-ad75-d089835248c4.png">

```
$ curl http://localhost:8081
Hello World!
```
